steps:
- uses: actions/checkout@v4

- name: Install Rust toolchain and target
  uses: actions-rs/toolchain@v1
  with:
    toolchain: stable
    override: true
    components: rust-src
    targets: thumbv7em-none-eabihf

- name: Build for embedded target
  run: cargo build --target thumbv7em-none-eabihf --verbose

# - name: Run host tests
#   run: cargo test --verbose
